// =========================================================================
// ⚔️ verbs_data.js - 變異動詞專屬彈藥庫 (純不規則版)
// =========================================================================

const irregularVerbs = [
    { base: 'awake', past: 'awoke', pp: 'awoken', zh: '喚醒/醒來', emoji: '😳', type: '不規則' },
    { base: 'be', past: 'was/were', pp: 'been', zh: '是', emoji: '👤', type: '不規則' },
    { base: 'bear', past: 'bore', pp: 'born/borne', zh: '忍受/生育', emoji: '🐻', type: '不規則' },
    { base: 'beat', past: 'beat', pp: 'beaten', zh: '擊打', emoji: '🥁', type: '不規則' },
    { base: 'become', past: 'became', pp: 'become', zh: '變成；成為', emoji: '✨', type: '不規則' },
    { base: 'begin', past: 'began', pp: 'begun', zh: '開始', emoji: '🚀', type: '不規則' },
    { base: 'bite', past: 'bit', pp: 'bitten', zh: '咬', emoji: '🦷', type: '不規則' },
    { base: 'bleed', past: 'bled', pp: 'bled', zh: '流血', emoji: '🩸', type: '不規則' },
    { base: 'blow', past: 'blew', pp: 'blown', zh: '吹', emoji: '🌬️', type: '不規則' },
    { base: 'break', past: 'broke', pp: 'broken', zh: '毀壞', emoji: '💔', type: '不規則' },
    { base: 'bring', past: 'brought', pp: 'brought', zh: '帶來', emoji: '🎁', type: '不規則' },
    { base: 'broadcast', past: 'broadcast', pp: 'broadcast', zh: '廣播', emoji: '📻', type: '不規則' },
    { base: 'build', past: 'built', pp: 'built', zh: '建造', emoji: '🏗️', type: '不規則' },
    { base: 'burn', past: 'burned/burnt', pp: 'burned/burnt', zh: '燃燒', emoji: '🔥', type: '不規則' },
    { base: 'burst', past: 'burst', pp: 'burst', zh: '爆裂', emoji: '💥', type: '不規則' },
    { base: 'buy', past: 'bought', pp: 'bought', zh: '買', emoji: '🛒', type: '不規則' },
    { base: 'catch', past: 'caught', pp: 'caught', zh: '抓', emoji: '🎣', type: '不規則' },
    { base: 'choose', past: 'chose', pp: 'chosen', zh: '選擇', emoji: '🗳️', type: '不規則' },
    { base: 'come', past: 'came', pp: 'come', zh: '來', emoji: '🏃‍♂️', type: '不規則' },
    { base: 'cost', past: 'cost', pp: 'cost', zh: '花費 (錢)', emoji: '💰', type: '不規則' },
    { base: 'cut', past: 'cut', pp: 'cut', zh: '切；割', emoji: '✂️', type: '不規則' },
    { base: 'deal', past: 'dealt', pp: 'dealt', zh: '處理/交易', emoji: '🤝', type: '不規則' },
    { base: 'dig', past: 'dug', pp: 'dug', zh: '挖掘', emoji: '⛏️', type: '不規則' },
    { base: 'do', past: 'did', pp: 'done', zh: '做', emoji: '✅', type: '不規則' },
    { base: 'draw', past: 'drew', pp: 'drawn', zh: '畫', emoji: '🎨', type: '不規則' },
    { base: 'dream', past: 'dreamed/dreamt', pp: 'dreamed/dreamt', zh: '夢想', emoji: '💭', type: '不規則' },
    { base: 'drink', past: 'drank', pp: 'drunk', zh: '喝', emoji: '🥛', type: '不規則' },
    { base: 'drive', past: 'drove', pp: 'driven', zh: '開 (車)', emoji: '🚗', type: '不規則' },
    { base: 'eat', past: 'ate', pp: 'eaten', zh: '吃', emoji: '🍴', type: '不規則' },
    { base: 'fall', past: 'fell', pp: 'fallen', zh: '跌倒', emoji: '🍂', type: '不規則' },
    { base: 'feed', past: 'fed', pp: 'fed', zh: '餵食', emoji: '🍼', type: '不規則' },
    { base: 'feel', past: 'felt', pp: 'felt', zh: '覺得', emoji: '😌', type: '不規則' },
    { base: 'fight', past: 'fought', pp: 'fought', zh: '對抗；打架', emoji: '🥊', type: '不規則' },
    { base: 'find', past: 'found', pp: 'found', zh: '找到', emoji: '🔍', type: '不規則' },
    { base: 'fly', past: 'flew', pp: 'flown', zh: '飛；飛行', emoji: '✈️', type: '不規則' },
    { base: 'forget', past: 'forgot', pp: 'forgotten', zh: '忘記', emoji: '❓', type: '不規則' },
    { base: 'forgive', past: 'forgave', pp: 'forgiven', zh: '原諒', emoji: '🙏', type: '不規則' },
    { base: 'freeze', past: 'froze', pp: 'frozen', zh: '結冰', emoji: '❄️', type: '不規則' },
    { base: 'get', past: 'got', pp: 'got/gotten', zh: '得到', emoji: '🤲', type: '不規則' },
    { base: 'give', past: 'gave', pp: 'given', zh: '給', emoji: '🎁', type: '不規則' },
    { base: 'go', past: 'went', pp: 'gone', zh: '去', emoji: '🏃', type: '不規則' },
    { base: 'grow', past: 'grew', pp: 'grown', zh: '成長', emoji: '🌱', type: '不規則' },
    { base: 'hang', past: 'hung', pp: 'hung', zh: '懸掛', emoji: '🖼️', type: '不規則' },
    { base: 'have', past: 'had', pp: 'had', zh: '有', emoji: '🤲', type: '不規則' },
    { base: 'hear', past: 'heard', pp: 'heard', zh: '聽到', emoji: '👂', type: '不規則' },
    { base: 'hide', past: 'hid', pp: 'hidden', zh: '躲藏', emoji: '🙈', type: '不規則' },
    { base: 'hit', past: 'hit', pp: 'hit', zh: '撞擊', emoji: '🔨', type: '不規則' },
    { base: 'hold', past: 'held', pp: 'held', zh: '握', emoji: '🤝', type: '不規則' },
    { base: 'hurt', past: 'hurt', pp: 'hurt', zh: '使受傷', emoji: '🤕', type: '不規則' },
    { base: 'keep', past: 'kept', pp: 'kept', zh: '持續；飼養', emoji: '🔁', type: '不規則' },
    { base: 'know', past: 'knew', pp: 'known', zh: '知道', emoji: '🧠', type: '不規則' },
    { base: 'lay', past: 'laid', pp: 'laid', zh: '下蛋/放置', emoji: '🥚', type: '不規則' },
    { base: 'lead', past: 'led', pp: 'led', zh: '領路；引導', emoji: '🚩', type: '不規則' },
    { base: 'learn', past: 'learned/learnt', pp: 'learned/learnt', zh: '學習', emoji: '🎓', type: '不規則' },
    { base: 'leave', past: 'left', pp: 'left', zh: '遺留；離開', emoji: '🚪', type: '不規則' },
    { base: 'lend', past: 'lent', pp: 'lent', zh: '借出', emoji: '🤝', type: '不規則' },
    { base: 'let', past: 'let', pp: 'let', zh: '讓/允許', emoji: '⭕', type: '不規則' },
    { base: 'lie', past: 'lay', pp: 'lain', zh: '躺', emoji: '🛌', type: '不規則' },
    { base: 'light', past: 'lit/lighted', pp: 'lit/lighted', zh: '點燃', emoji: '💡', type: '不規則' },
    { base: 'lose', past: 'lost', pp: 'lost', zh: '輸掉', emoji: '👎', type: '不規則' },
    { base: 'make', past: 'made', pp: 'made', zh: '製作', emoji: '🛠️', type: '不規則' },
    { base: 'mean', past: 'meant', pp: 'meant', zh: '意指', emoji: '💬', type: '不規則' },
    { base: 'meet', past: 'met', pp: 'met', zh: '遇見', emoji: '👋', type: '不規則' },
    { base: 'mistake', past: 'mistook', pp: 'mistaken', zh: '犯錯/誤認', emoji: '❌', type: '不規則' },
    { base: 'overcome', past: 'overcame', pp: 'overcome', zh: '克服', emoji: '🏔️', type: '不規則' },
    { base: 'pay', past: 'paid', pp: 'paid', zh: '付 (錢)', emoji: '💳', type: '不規則' },
    { base: 'put', past: 'put', pp: 'put', zh: '放', emoji: '📥', type: '不規則' },
    { base: 'quit', past: 'quit', pp: 'quit', zh: '放棄/退出', emoji: '🚪', type: '不規則' },
    { base: 'read', past: 'read', pp: 'read', zh: '閱讀', emoji: '📖', type: '不規則' },
    { base: 'ride', past: 'rode', pp: 'ridden', zh: '騎', emoji: '🚲', type: '不規則' },
    { base: 'ring', past: 'rang', pp: 'rung', zh: '鳴/響', emoji: '🔔', type: '不規則' },
    { base: 'rise', past: 'rose', pp: 'risen', zh: '升起', emoji: '🌅', type: '不規則' },
    { base: 'run', past: 'ran', pp: 'run', zh: '跑', emoji: '👟', type: '不規則' },
    { base: 'say', past: 'said', pp: 'said', zh: '說', emoji: '🗣️', type: '不規則' },
    { base: 'see', past: 'saw', pp: 'seen', zh: '看', emoji: '👁️', type: '不規則' },
    { base: 'seek', past: 'sought', pp: 'sought', zh: '尋找', emoji: '🔭', type: '不規則' },
    { base: 'sell', past: 'sold', pp: 'sold', zh: '賣', emoji: '💰', type: '不規則' },
    { base: 'send', past: 'sent', pp: 'sent', zh: '寄；送', emoji: '✉️', type: '不規則' },
    { base: 'set', past: 'set', pp: 'set', zh: '設定；放置', emoji: '⚙️', type: '不規則' },
    { base: 'shake', past: 'shook', pp: 'shaken', zh: '搖動', emoji: '🫨', type: '不規則' },
    { base: 'shine', past: 'shined/shone', pp: 'shined/shone', zh: '照耀', emoji: '✨', type: '不規則' },
    { base: 'shoot', past: 'shot', pp: 'shot', zh: '射擊', emoji: '🔫', type: '不規則' },
    { base: 'show', past: 'showed', pp: 'shown', zh: '展示', emoji: '📺', type: '不規則' },
    { base: 'shrink', past: 'shrank/shrunk', pp: 'shrunk', zh: '縮水', emoji: '👕', type: '不規則' },
    { base: 'shut', past: 'shut', pp: 'shut', zh: '關閉', emoji: '🚪', type: '不規則' },
    { base: 'sing', past: 'sang', pp: 'sung', zh: '唱', emoji: '🎤', type: '不規則' },
    { base: 'sink', past: 'sank', pp: 'sunk', zh: '下沉', emoji: '⚓', type: '不規則' },
    { base: 'sit', past: 'sat', pp: 'sat', zh: '坐', emoji: '🪑', type: '不規則' },
    { base: 'sleep', past: 'slept', pp: 'slept', zh: '睡覺', emoji: '😴', type: '不規則' },
    { base: 'slide', past: 'slid', pp: 'slid', zh: '滑動', emoji: '🛝', type: '不規則' },
    { base: 'smell', past: 'smelled/smelt', pp: 'smelled/smelt', zh: '聞起來', emoji: '👃', type: '不規則' },
    { base: 'speak', past: 'spoke', pp: 'spoken', zh: '說；說話', emoji: '🗣️', type: '不規則' },
    { base: 'speed', past: 'sped/speeded', pp: 'sped/speeded', zh: '加速', emoji: '🏎️', type: '不規則' },
    { base: 'spell', past: 'spelled/spelt', pp: 'spelled/spelt', zh: '拼字', emoji: '🔤', type: '不規則' },
    { base: 'spend', past: 'spent', pp: 'spent', zh: '花費/花時間', emoji: '💸', type: '不規則' },
    { base: 'spill', past: 'spilled/spilt', pp: 'spilled/spilt', zh: '灑出', emoji: '💦', type: '不規則' },
    { base: 'spread', past: 'spread', pp: 'spread', zh: '傳播/散佈', emoji: '📢', type: '不規則' },
    { base: 'stand', past: 'stood', pp: 'stood', zh: '站', emoji: '🧍', type: '不規則' },
    { base: 'steal', past: 'stole', pp: 'stolen', zh: '偷竊', emoji: '🥷', type: '不規則' },
    { base: 'stick', past: 'stuck', pp: 'stuck', zh: '黏貼/刺', emoji: '📌', type: '不規則' },
    { base: 'strike', past: 'struck', pp: 'struck', zh: '打擊', emoji: '⚾', type: '不規則' },
    { base: 'swear', past: 'swore', pp: 'sworn', zh: '發誓', emoji: '🤞', type: '不規則' },
    { base: 'sweep', past: 'swept', pp: 'swept', zh: '掃', emoji: '🧹', type: '不規則' },
    { base: 'swim', past: 'swam', pp: 'swum', zh: '游泳', emoji: '🏊', type: '不規則' },
    { base: 'swing', past: 'swung', pp: 'swung', zh: '搖擺', emoji: '🎢', type: '不規則' },
    { base: 'take', past: 'took', pp: 'taken', zh: '拿', emoji: '👜', type: '不規則' },
    { base: 'teach', past: 'taught', pp: 'taught', zh: '教學', emoji: '👨‍🏫', type: '不規則' },
    { base: 'tear', past: 'tore', pp: 'torn', zh: '撕裂', emoji: '📄', type: '不規則' },
    { base: 'tell', past: 'told', pp: 'told', zh: '告訴', emoji: '💬', type: '不規則' },
    { base: 'think', past: 'thought', pp: 'thought', zh: '想；認為', emoji: '🤔', type: '不規則' },
    { base: 'throw', past: 'threw', pp: 'thrown', zh: '丟', emoji: '⚾', type: '不規則' },
    { base: 'understand', past: 'understood', pp: 'understood', zh: '了解', emoji: '💡', type: '不規則' },
    { base: 'upset', past: 'upset', pp: 'upset', zh: '使心煩/打亂', emoji: '😠', type: '不規則' },
    { base: 'wake', past: 'woke', pp: 'woken', zh: '醒來', emoji: '⏰', type: '不規則' },
    { base: 'wear', past: 'wore', pp: 'worn', zh: '穿；戴', emoji: '👕', type: '不規則' },
    { base: 'win', past: 'won', pp: 'won', zh: '贏；獲勝', emoji: '🏆', type: '不規則' },
    { base: 'write', past: 'wrote', pp: 'written', zh: '寫', emoji: '✍️', type: '不規則' }
];

// 📦 組合最終兵器庫 (現在 100% 都是變異體)
const allVerbs = [...irregularVerbs];